# Generated by Django 3.2.5 on 2022-04-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_shift', models.CharField(max_length=2)),
                ('masuk', models.TimeField()),
                ('pulang', models.TimeField()),
            ],
        ),
    ]
