# Generated by Django 4.0.2 on 2022-04-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=18)),
                ('nama', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('nohp', models.CharField(max_length=12)),
                ('alamat', models.TextField(blank=True)),
                ('foto', models.TextField(blank=True)),
                ('jabatan', models.CharField(max_length=200)),
                ('shift', models.CharField(default='1', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
