# Generated by Django 4.0.2 on 2022-04-13 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_pegawai_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jabatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_jabatan', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Presensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=18)),
                ('nama', models.CharField(max_length=255)),
                ('tanggal', models.DateField()),
                ('check_in', models.TimeField()),
                ('late_in', models.CharField(max_length=3)),
                ('check_out', models.TimeField()),
                ('ket', models.CharField(max_length=100)),
                ('suhu', models.CharField(max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='shift',
            name='id',
        ),
        migrations.AlterField(
            model_name='pegawai',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.shift'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='id_shift',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pegawai',
            name='jabatan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.jabatan'),
        ),
    ]
